import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
import { Current } from './types/current';
import { Locations, SearchData } from './types/search';

export const api = createApi({
  reducerPath: 'api',
  baseQuery: fetchBaseQuery({
    baseUrl: 'http://api.weatherapi.com/v1/',
  }),
  endpoints: (builder) => ({
    getLocationByName: builder.query<Locations[], SearchData>({
      query: (searchData) => `search.json?key=${searchData.key}&q=${searchData.value}`,
    }),
    getCurrentWeatherByLocation: builder.query<Current[], SearchData>({
      query: (weatherData) => `current.json?key=${weatherData.key}&q=${weatherData.value}&aqi=yes`,
    }),
  }),
});

export const { useGetLocationByNameQuery, useLazyGetCurrentWeatherByLocationQuery } = api;

// Generated by https://quicktype.io
